name: CVChat
main: org.cubeville.cvchat.CVChat
authors: [FrediW]
version: 0.1
depend: [CVIPC]

commands:
  modreq:
    description: Send moderator request
  unlocktutorialchat:
    description: Unlocks tutorial chat
  ltr:
    description: Fake local chat
    permission: cvchat.fakelocal
